### ISSUE TITLE
tracker managed一项始终为空，怎么回事

### ISSUE THREAD

**Issue by cjsjy123** [PerfAssist/PA_ResourceTracker#7]

**Comment by virtual-serenity** [comment]
抱歉，这里的几个限制此前没有讲明白。现阶段 Unity 获取内存信息的接口有下面的限制：

1. 需要较新的 Unity 版本。目前根据知乎朋友的测试，已知的是 **5.3.4p1 还不能获取 managed 而 5.3.6 及以上就可以**。
2. 需要运行在 ios 真机上 (**必须以 il2cpp 方式构建**才可以获取 managed 信息)

如果这两个条件都满足了还是没有 managed 对象，麻烦回到这里跟我讲一声:smile:
