### ISSUE TITLE
unity5.4.1上运行报错

### ISSUE THREAD

**Issue by Greensue** [PerfAssist/PA_ResourceTracker#8]
您好：
     你们的工作真的十分有意义，但是我在unity5.4.1上运行这个工程的时候提示错误：
Assets/PerfAssist/ResourceTracker/ResourceTracker.cs(358,47): error CS0246: The type or namespace name `eNetCmd' could not be found. Are you missing a using directive or an assembly reference?
是这个里面少了一些文件吗？怎样解决，十分感谢！

**Comment by virtual-serenity** [comment]
需要更新子模块~~  TortoistGit -> Submodule Update...
