### ISSUE TITLE
Can't save a snapshot (or at least not under an hour)

### ISSUE THREAD

**Issue by cAyou** [PerfAssist/PA_ResourceTracker#9]
Hi ! On our game it's close to impossible for me to save a snapshot. I wait like for an hour after clicking the button, I can see that Unity is still working on it (the process is on and the mem file is getting bigger), the file size goes to like 120mb. I don't really tested to let Unity finishes it, but more than an hour to save a snapshot that takes 25sec to take it's a bit annoying...
On another big project it takes a few seconds and the file size is about 3mb.
How can I get around it? Thanks !

PS: using Unity 5.6.4f1.

**Comment by virtual-serenity** [comment]
Is it 100% reproducible, even in a very simple scene (eg. your title screen)?

A typical snapshot capturing process for an il2cpp-based Unity app would take around **1-3 minutes**, depends on the project size (specifically, the underlying memory layout complexity of the il2cpp-based C# vm status).

In practice, there are several issues that you should be aware of (as we already met),

- The app crashes shortly after `Take Snapshot` is clicked.
    + It's most possibly because of **out-of-memory**. The snapshot *internally* takes additional memory to function properly, which may vary from 10MB to 100+MB, depends on the project size. The app would be killed quickly if the consumed memory is already somewhere nearby the 'warn-and-kill bar' of the system. 
    + So make sure you are using a large-memory device (like iPhone 6 Plus) for memory diagnosing, or leave enough space for the memory profiler.
- The memory profiler panel hangs for an unreasonable long time after `Take Snapshot` is clicked (while the app itself returns back to responsive running)
    + Unity memory profiler is sharing the internal connection with its profiler panel, which is apparently not stable enough especially when you have weak wifi signal, large `.memsnap`, etc... Internally we use a in-house debugging utility to generate the `.memsnap` file on-the-fly and save it directly on device, and then pull it back to editor using our own connection, in a much more stable manner. Since it involves works from others in our team, we haven't considered to open-source it yet.

It surely has glitches but generally works in 80% time, so please be a little patient with it and it would return much valuable information.

We are actively making changes to this tool and you may already find that the description in README.md file is heavily outdated. So stay tuned for the improved releases later.

**Comment by meichaoge** [comment]
you may miss submit some scripts :eNetCmd/UsCmd/UsMain .They Can't Be Found

**Comment by virtual-serenity** [comment]
@meichaoge Did you `git submodule update...` ?

**Comment by cAyou** [comment]
@mc-gulu thanks for replying ! I've managed to save a snapshot of the main menu, where there is not a lot of objects. The snapshot takes about a second to create and 30 to save. I will wait for a new version for sure, the tool was already pretty useful to me (coupled with a tool where you can see all hidden objects in the scene), I discovered a lot of surprises in our game...
Right now I'm using the tool directly inside the project I'm running, either from an editor run or from a build recently made. Do you think it's better to put the tool on another project instead of running it from  the tested project itself?

**Comment by virtual-serenity** [comment]
@cAyou both of them should work. Please note this tool has been moved to a new location.
